### ISSUE TITLE
NiceModalProps should let objects with id

### ISSUE THREAD

**Issue by osrl** [eBay/nice-modal-react#106]
NiceModalHocProps has a field named id. This is too common and prevents us to pass a type with id in it. 

This is not possible:
```typescript
NiceModal.create(
  (object: { id: string; foo: string }) => { ... }
```

I actually opened a PR for this #96. But closed it since it wasn't backward compatible. 

To reproduce:

```typescript
export const FoodModal = NiceModal.create(
  (arg: { id: string }) => {

    return (
      <div></div>
    );
  }
);


NiceModal.show(FoodModal, {id: "foo"}) // No overload matches this call
```

```typescript
export const FoodModal = NiceModal.create(
  (arg: { fooId: string }) => {

    return (
      <div></div>
    );
  }
);


NiceModal.show(FoodModal, {fooId: "foo"}) // It's okay now
```

**Comment by supnate** [comment]
hmm, I remember calling `modal.show(modal, args)` can use any prop name.

**Comment by czkoudy** [comment]
Hi @supnate any luck with this?

**Comment by supnate** [comment]
Type check now fixed in [v1.2.12](https://github.com/eBay/nice-modal-react/releases/tag/1.2.12). You can use `id` prop now.

**Comment by chj-damon** [comment]
@supnate I'm using 1.2.13 and still facing the same problem. typescript still reports error because I passed id prop as number type
